In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname = "C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc("font", family= font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

## 1. 가장 많이 이용하는 ott 서비스 1순위 

### 성별/나이별/소득별/지역/가구원수1

소득별은 왜? - 구독료가 있으니까 소득별로 구독하는 ott가 다를까 ?

+ 구분별, 왜 선택 했는지 이유가 들어가면 좋을것 같음- 가설 설정?

### 1)  데이터 전처리

In [4]:
# 엑셀 파일 불러오기

ott_s = pd.read_excel("가장_많이_이용하는_OTT_서비스_1순위.xlsx",  header=[0,1], index_col=[0,1])
ott_s

C:\Users\LG\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

구분별(2)               2020                                               \
구분별(2)            사례수 (명) 티빙(Tving) (%) 웨이브(Wavve)(구 푹(pooq), 옥수수) (%)
전체    소계             7434           4.4                            4.0
성별    남              3872           3.9                            3.9
      여              3562           4.9                            4.0
연령    만10대미만          173           1.2                            0.0
      만10-19세         825           3.8                            1.0
      만20-29세        1378           6.3                            3.8
      만30-39세        1420           4.3                            8.1
      만40-49세        1481           5.2                            4.3
      만50-59세        1373           3.8                            2.0
      만60-69세         666           2.2                            3.8
      만70세이상          119           1.1                            4.1
월평균소득 소득없음           2477           4.7                            2.3
      50만원미만          138           9.6                            2.6
      50-100만원미만      222           2.2                            4.3
      100-200만원미만    1120           4.9                            4.7
      200-300만원미만    1961           4.2                            5.0
      300-400만원미만    1026           3.6                            5.6
      400-500만원미만     266           4.8                            1.1
      500만원이상         224           1.6                            7.1
지역    서울             1482           4.4                            6.2
      부산              524           0.2                            0.7
      대구              335           3.9                            3.1
      인천              452           1.9                            3.5
      광주              248           5.6                            0.3
      대전              213           1.3                            4.0
      울산              176           0.2                            1.8
      경기             1907           9.5                            4.9
      강원              181           0.3                            1.6
      충북              264           2.2                            1.2
      충남              265           3.2                            7.1
      전북              262           2.2                            0.4
      전남              245           4.7                            0.7
      경북              291           0.8                           11.0
      경남              427           0.4                            1.5
      제주               83           0.3                            2.9
      세종               79           4.0                            0.0
가구원수1 1인가구            822           1.5                            8.4
      2인가구           1586           4.9                            3.6
      3인이상가구         5027           4.7                            3.4

구분별(2)                                                                    \
구분별(2)            KT 시즌(Seezn)(구 olleh tv 모바일) (%) U+ 모바일(구 U+비디오포털) (%)
전체    소계                                       1.0                   1.3
성별    남                                        1.1                   1.3
      여                                        0.8                   1.3
연령    만10대미만                                   2.7                   0.0
      만10-19세                                  0.5                   0.5
      만20-29세                                  0.7                   0.9
      만30-39세                                  0.6                   1.5
      만40-49세                                  1.2                   2.5
      만50-59세                                  0.9                   0.8
      만60-69세                                  1.9                   1.1
      만70세이상                                   2.5                   1.8
월평균소득 소득없음                                     0.8                   0.9
      50만원미만                                   1.9                   2.3
      50-100만원미만                               3.0                   3.6
      100-200만원미만                              0.9                   0.8
      200-300만원미만                              0.6                   0.9
      300-400만원미만                              1.5                   2.5
      400-500만원미만                              1.3                   2.1
      500만원이상                                  1.7                   1.5
지역    서울                                       1.2                   2.9
      부산                                       0.0                   0.7
      대구                                       1.5                   1.2
      인천                                       0.4                   0.3
      광주                                       0.0                   0.0
      대전                                       0.2                   0.0
      울산                                       2.0                   1.0
      경기                                       1.4                   1.5
      강원                                       2.6                   1.5
      충북                                       0.0                   0.1
      충남                                       0.3                   0.8
      전북                                       0.0                   0.3
      전남                                       0.0                   0.0
      경북                                       1.2                   1.1
      경남                                       0.9                   0.5
      제주                                       6.0                   1.4
      세종                                       0.0                   0.0
가구원수1 1인가구                                     0.5                   0.8
      2인가구                                     0.5                   0.6
      3인이상가구                                   1.2                   1.6

구분별(2)                                                                  \
구분별(2)            에브리온 TV (%) 네이버시리즈(구 네이버 N 스토어) (%) 곰TV (%) 넷플릭스 (%)
전체    소계                  0.0                     0.7     0.2      7.1
성별    남                   0.0                     0.7     0.2      6.5
      여                   0.1                     0.6     0.1      7.8
연령    만10대미만              0.0                     0.0     0.0      0.9
      만10-19세             0.0                     0.4     0.1      4.6
      만20-29세             0.0                     0.6     0.1     13.1
      만30-39세             0.0                     0.7     0.3      9.5
      만40-49세             0.2                     0.9     0.2      7.7
      만50-59세             0.0                     1.1     0.1      3.8
      만60-69세             0.0                     0.4     0.0      1.2
      만70세이상              0.0                     0.0     0.0      0.0
월평균소득 소득없음                0.1                     0.6     0.1      5.5
      50만원미만              0.0                     0.0     0.0      6.2
      50-100만원미만          0.0                     0.9     0.0      8.0
      100-200만원미만         0.1                     0.2     0.3      5.2
      200-300만원미만         0.0                     0.5     0.1      8.6
      300-400만원미만         0.1                     1.2     0.4      9.5
      400-500만원미만         0.0                     2.0     0.0     11.8
      500만원이상             0.0                     1.8     0.4      4.8
지역    서울                  0.1                     0.6     0.1     12.3
      부산                  0.0                     1.1     0.0      5.2
      대구                  0.0                     1.4     0.3      9.5
      인천                  0.0                     1.3     0.0      5.1
      광주                  0.0                     0.0     0.0      4.6
      대전                  0.0                     0.0     1.4      6.3
      울산                  0.0                     0.9     0.0      1.2
      경기                  0.1                     0.8     0.0      6.6
      강원                  0.0                     0.0     0.0      6.8
      충북                  0.0                     0.0     1.4      7.7
      충남                  0.0                     0.9     0.0      1.9
      전북                  0.0                     0.0     0.2      9.6
      전남                  0.0                     0.4     0.2      3.6
      경북                  0.0                     1.1     0.2      4.4
      경남                  0.0                     0.5     0.2      4.3
      제주                  0.0                     1.1     0.0      3.7
      세종                  0.0                     0.0     0.0      7.8
가구원수1 1인가구                0.0                     0.0     0.0      9.6
      2인가구                0.0                     0.8     0.0      6.5
      3인이상가구              0.1                     0.8     0.2      6.9

구분별(2)                        ...                    2021                   \
구분별(2)            카카오 TV (%)  ... 네이버시리즈(구 네이버 N 스토어) (%) 곰TV (%) 넷플릭스 (%)
전체    소계                 1.6  ...                     0.3     0.2      8.8
성별    남                  1.6  ...                     0.3     0.2      8.1
      여                  1.7  ...                     0.4     0.1      9.5
연령    만10대미만             0.0  ...                     0.0     0.0      6.2
      만10-19세            1.3  ...                     0.1     0.2      6.8
      만20-29세            1.9  ...                     0.5     0.2     17.1
      만30-39세            1.2  ...                     0.3     0.3     11.3
      만40-49세            1.0  ...                     0.5     0.1     11.1
      만50-59세            2.1  ...                     0.3     0.3      4.7
      만60-69세            2.7  ...                     0.3     0.1      1.3
      만70세이상             3.6  ...                     0.0     0.0      0.4
월평균소득 소득없음               1.0  ...                     0.4     0.1      8.4
      50만원미만             0.5  ...                     0.0     0.0      6.8
      50-100만원미만         1.2  ...                     0.0     0.0      5.8
      100-200만원미만        4.1  ...                     0.1     0.3      9.5
      200-300만원미만        1.3  ...                     0.2     0.1      8.9
      300-400만원미만        1.3  ...                     0.3     0.5      7.9
      400-500만원미만        1.1  ...                     1.0     0.0     15.4
      500만원이상            1.8  ...                     1.2     0.0      9.1
지역    서울                 2.2  ...                     0.4     0.2      8.8
      부산                 1.1  ...                     0.0     0.0      5.3
      대구                 1.8  ...                     1.4     0.7     16.2
      인천                 0.8  ...                     0.7     0.0      7.9
      광주                 1.5  ...                     0.0     0.0      5.3
      대전                 3.0  ...                     0.0     0.0      9.4
      울산                 0.4  ...                     0.0     0.0      8.5
      경기                 1.8  ...                     0.4     0.4     11.4
      강원                 0.0  ...                     0.0     0.0      9.1
      충북                 2.0  ...                     0.1     0.0      6.4
      충남                 1.7  ...                     0.0     0.0      7.6
      전북                 2.0  ...                     0.3     0.2      2.9
      전남                 0.8  ...                     0.1     0.0      0.5
      경북                 0.8  ...                     1.0     0.2      3.7
      경남                 1.8  ...                     0.0     0.0      9.1
      제주                 0.0  ...                     0.0     0.0      6.0
      세종                 0.8  ...                     0.0     0.0     23.9
가구원수1 1인가구               1.6  ...                     0.3     0.0     10.8
      2인가구               2.5  ...                     0.1     0.0      6.7
      3인이상가구             1.4  ...                     0.4     0.3      9.2

구분별(2)                                                                    \
구분별(2)            카카오 TV (%) 유튜브 (%) 아마존 프라임 비디오 (%) 왓챠플레이 (%) 쿠팡플레이 (%)
전체    소계                 1.8    81.5             0.0       0.2       0.2
성별    남                  1.6    82.6             0.0       0.1       0.1
      여                  2.0    80.3             0.0       0.3       0.3
연령    만10대미만             0.0    90.2             0.0       0.0       0.0
      만10-19세            3.5    86.2             0.0       0.4       0.0
      만20-29세            1.4    70.3             0.0       0.6       0.1
      만30-39세            2.1    74.2             0.0       0.3       0.5
      만40-49세            2.0    77.4             0.0       0.1       0.4
      만50-59세            1.6    87.8             0.0       0.0       0.0
      만60-69세            0.3    94.2             0.0       0.0       0.0
      만70세이상             2.3    94.0             0.0       0.0       0.0
월평균소득 소득없음               2.1    83.3             0.0       0.4       0.1
      50만원미만             0.5    88.4             0.0       0.0       0.5
      50-100만원미만         0.3    87.5             0.0       0.5       1.0
      100-200만원미만        2.2    82.3             0.1       0.0       0.1
      200-300만원미만        1.4    80.6             0.0       0.2       0.3
      300-400만원미만        1.6    79.2             0.0       0.0       0.2
      400-500만원미만        3.3    71.7             0.0       0.2       0.0
      500만원이상            1.2    80.2             0.2       0.0       0.0
지역    서울                 2.1    75.6             0.0       0.4       0.4
      부산                 0.5    92.8             0.0       0.0       0.0
      대구                 6.2    66.3             0.0       0.2       0.0
      인천                 0.7    84.2             0.1       0.0       0.7
      광주                 1.1    91.9             0.0       0.2       0.0
      대전                 1.2    88.6             0.0       0.0       0.0
      울산                 0.0    88.0             0.0       0.0       0.0
      경기                 2.6    74.8             0.0       0.4       0.2
      강원                 0.6    83.2             0.3       0.0       0.0
      충북                 0.9    91.6             0.0       0.0       0.0
      충남                 1.1    90.4             0.0       0.0       0.0
      전북                 3.2    88.4             0.0       0.0       0.0
      전남                 0.9    94.9             0.1       0.0       0.0
      경북                 0.8    86.6             0.0       0.0       0.2
      경남                 0.1    88.4             0.0       0.0       0.0
      제주                 0.2    85.8             0.0       0.0       2.0
      세종                 0.0    76.1             0.0       0.0       0.0
가구원수1 1인가구               2.3    74.0             0.0       0.0       0.2
      2인가구               0.9    86.1             0.0       0.0       0.1
      3인이상가구             2.0    81.1             0.0       0.3       0.2

구분별(2)
구분별(2)            아프리카 TV (%) 기타 (%)
전체    소계                  0.3    0.0
성별    남                   0.5    0.1
      여                   0.1    0.0
연령    만10대미만              0.0    0.4
      만10-19세             0.1    0.1
      만20-29세             1.5    0.1
      만30-39세             0.0    0.0
      만40-49세             0.1    0.0
      만50-59세             0.1    0.0
      만60-69세             0.0    0.0
      만70세이상              0.0    0.0
월평균소득 소득없음                0.4    0.1
      50만원미만              0.0    0.0
      50-100만원미만          0.0    0.0
      100-200만원미만         0.0    0.1
      200-300만원미만         0.6    0.0
      300-400만원미만         0.2    0.0
      400-500만원미만         0.0    0.0
      500만원이상             0.1    0.0
지역    서울                  0.0    0.0
      부산                  0.2    0.0
      대구                  0.4    0.2
      인천                  0.3    0.2
      광주                  0.0    0.0
      대전                  0.0    0.0
      울산                  0.0    0.0
      경기                  0.6    0.0
      강원                  0.3    0.0
      충북                  0.0    0.0
      충남                  0.0    0.0
      전북                  0.0    0.0
      전남                  2.6    0.0
      경북                  0.0    0.0
      경남                  0.2    0.0
      제주                  0.0    1.2
      세종                  0.0    0.0
가구원수1 1인가구                0.0    0.0
      2인가구                0.4    0.0
      3인이상가구              0.3    0.1

[39 rows x 29 columns]

In [5]:
# 컬럼 명 변경

ott_s.columns =[["2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020",
               "2021","2021","2021","2021","2021","2021","2021","2021","2021","2021","2021","2021","2021","2021","2021"],
              ["명 수","티빙", "웨이브", "KT_Seezn", "U+모바일", "에브리온TV", "네이버시리즈", "곰TV", "넷플릭스","카카오TV", "유튜브프리미엄", "아마존프라임", "왓챠플레이","기타",
              "명 수","티빙", "웨이브", "KT_Seezn", "U+모바일", "네이버시리즈", "곰TV", "넷플릭스","카카오TV", "유튜브프리미엄", "아마존프라임", "왓챠플레이","쿠팡플레이","아프리카TV","기타"]]

In [7]:
ott_s.info()
ott_s

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 39 entries, ('전체', '소계') to ('가구원수1', '3인이상가구')
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   (2020, 명 수)       39 non-null     int64
 1   (2020, 티빙)        39 non-null     float64
 2   (2020, 웨이브)       39 non-null     float64
 3   (2020, KT_Seezn)  39 non-null     float64
 4   (2020, U+모바일)     39 non-null     float64
 5   (2020, 에브리온TV)    39 non-null     float64
 6   (2020, 네이버시리즈)    39 non-null     float64
 7   (2020, 곰TV)       39 non-null     float64
 8   (2020, 넷플릭스)      39 non-null     float64
 9   (2020, 카카오TV)     39 non-null     float64
 10  (2020, 유튜브프리미엄)   39 non-null     float64
 11  (2020, 아마존프라임)    39 non-null     float64
 12  (2020, 왓챠플레이)     39 non-null     float64
 13  (2020, 기타)        39 non-null     float64
 14  (2021, 명 수)       39 non-null     float64
 15  (2021, 티빙)        39 non-null     float64
 16  (2021, 웨이브)       39 non-null     float64
 17  (2021, KT_Seezn)  39 non-null     float64
 18  (2021, U+모바일)     39 non-null     float64
 19  (2021, 네이버시리즈)    39 non-null     float64
 20  (2021, 곰TV)       39 non-null     float64
 21  (2021, 넷플릭스)      39 non-null     float64
 22  (2021, 카카오TV)     39 non-null     float64
 23  (2021, 유튜브프리미엄)   39 non-null     float64
 24  (2021, 아마존프라임)    39 non-null     float64
 25  (2021, 왓챠플레이)     39 non-null     float64
 26  (2021, 쿠팡플레이)     39 non-null     float64
 27  (2021, 아프리카TV)    39 non-null     float64
 28  (2021, 기타)        39 non-null     float64
dtypes: float64(28), int64(1)
memory usage: 10.5+ KB

                   2020                                                     \
                    명 수   티빙   웨이브 KT_Seezn U+모바일 에브리온TV 네이버시리즈  곰TV  넷플릭스
전체    소계           7434  4.4   4.0      1.0   1.3    0.0    0.7  0.2   7.1
성별    남            3872  3.9   3.9      1.1   1.3    0.0    0.7  0.2   6.5
      여            3562  4.9   4.0      0.8   1.3    0.1    0.6  0.1   7.8
연령    만10대미만        173  1.2   0.0      2.7   0.0    0.0    0.0  0.0   0.9
      만10-19세       825  3.8   1.0      0.5   0.5    0.0    0.4  0.1   4.6
      만20-29세      1378  6.3   3.8      0.7   0.9    0.0    0.6  0.1  13.1
      만30-39세      1420  4.3   8.1      0.6   1.5    0.0    0.7  0.3   9.5
      만40-49세      1481  5.2   4.3      1.2   2.5    0.2    0.9  0.2   7.7
      만50-59세      1373  3.8   2.0      0.9   0.8    0.0    1.1  0.1   3.8
      만60-69세       666  2.2   3.8      1.9   1.1    0.0    0.4  0.0   1.2
      만70세이상        119  1.1   4.1      2.5   1.8    0.0    0.0  0.0   0.0
월평균소득 소득없음         2477  4.7   2.3      0.8   0.9    0.1    0.6  0.1   5.5
      50만원미만        138  9.6   2.6      1.9   2.3    0.0    0.0  0.0   6.2
      50-100만원미만    222  2.2   4.3      3.0   3.6    0.0    0.9  0.0   8.0
      100-200만원미만  1120  4.9   4.7      0.9   0.8    0.1    0.2  0.3   5.2
      200-300만원미만  1961  4.2   5.0      0.6   0.9    0.0    0.5  0.1   8.6
      300-400만원미만  1026  3.6   5.6      1.5   2.5    0.1    1.2  0.4   9.5
      400-500만원미만   266  4.8   1.1      1.3   2.1    0.0    2.0  0.0  11.8
      500만원이상       224  1.6   7.1      1.7   1.5    0.0    1.8  0.4   4.8
지역    서울           1482  4.4   6.2      1.2   2.9    0.1    0.6  0.1  12.3
      부산            524  0.2   0.7      0.0   0.7    0.0    1.1  0.0   5.2
      대구            335  3.9   3.1      1.5   1.2    0.0    1.4  0.3   9.5
      인천            452  1.9   3.5      0.4   0.3    0.0    1.3  0.0   5.1
      광주            248  5.6   0.3      0.0   0.0    0.0    0.0  0.0   4.6
      대전            213  1.3   4.0      0.2   0.0    0.0    0.0  1.4   6.3
      울산            176  0.2   1.8      2.0   1.0    0.0    0.9  0.0   1.2
      경기           1907  9.5   4.9      1.4   1.5    0.1    0.8  0.0   6.6
      강원            181  0.3   1.6      2.6   1.5    0.0    0.0  0.0   6.8
      충북            264  2.2   1.2      0.0   0.1    0.0    0.0  1.4   7.7
      충남            265  3.2   7.1      0.3   0.8    0.0    0.9  0.0   1.9
      전북            262  2.2   0.4      0.0   0.3    0.0    0.0  0.2   9.6
      전남            245  4.7   0.7      0.0   0.0    0.0    0.4  0.2   3.6
      경북            291  0.8  11.0      1.2   1.1    0.0    1.1  0.2   4.4
      경남            427  0.4   1.5      0.9   0.5    0.0    0.5  0.2   4.3
      제주             83  0.3   2.9      6.0   1.4    0.0    1.1  0.0   3.7
      세종             79  4.0   0.0      0.0   0.0    0.0    0.0  0.0   7.8
가구원수1 1인가구          822  1.5   8.4      0.5   0.8    0.0    0.0  0.0   9.6
      2인가구         1586  4.9   3.6      0.5   0.6    0.0    0.8  0.0   6.5
      3인이상가구       5027  4.7   3.4      1.2   1.6    0.1    0.8  0.2   6.9

                         ...   2021                                        \
                  카카오TV  ... 네이버시리즈  곰TV  넷플릭스 카카오TV 유튜브프리미엄 아마존프라임 왓챠플레이
전체    소계            1.6  ...    0.3  0.2   8.8   1.8    81.5    0.0   0.2
성별    남             1.6  ...    0.3  0.2   8.1   1.6    82.6    0.0   0.1
      여             1.7  ...    0.4  0.1   9.5   2.0    80.3    0.0   0.3
연령    만10대미만        0.0  ...    0.0  0.0   6.2   0.0    90.2    0.0   0.0
      만10-19세       1.3  ...    0.1  0.2   6.8   3.5    86.2    0.0   0.4
      만20-29세       1.9  ...    0.5  0.2  17.1   1.4    70.3    0.0   0.6
      만30-39세       1.2  ...    0.3  0.3  11.3   2.1    74.2    0.0   0.3
      만40-49세       1.0  ...    0.5  0.1  11.1   2.0    77.4    0.0   0.1
      만50-59세       2.1  ...    0.3  0.3   4.7   1.6    87.8    0.0   0.0
      만60-69세       2.7  ...    0.3  0.1   1.3   0.3    94.2    0.0   0.0
      만70세이상        3.6  ...    0.0  0.0   0.4   2.3    94.0    0.0   0.0
월평균소득 소득없음          1.0  ...    0.4  0.1   8.4   2.1    83.3    0.0   0.4
      50만원미만        0.5  ...    0.0  0.0   6.8   0.5    88.4    0.0   0.0
      50-100만원미만    1.2  ...    0.0  0.0   5.8   0.3    87.5    0.0   0.5
      100-200만원미만   4.1  ...    0.1  0.3   9.5   2.2    82.3    0.1   0.0
      200-300만원미만   1.3  ...    0.2  0.1   8.9   1.4    80.6    0.0   0.2
      300-400만원미만   1.3  ...    0.3  0.5   7.9   1.6    79.2    0.0   0.0
      400-500만원미만   1.1  ...    1.0  0.0  15.4   3.3    71.7    0.0   0.2
      500만원이상       1.8  ...    1.2  0.0   9.1   1.2    80.2    0.2   0.0
지역    서울            2.2  ...    0.4  0.2   8.8   2.1    75.6    0.0   0.4
      부산            1.1  ...    0.0  0.0   5.3   0.5    92.8    0.0   0.0
      대구            1.8  ...    1.4  0.7  16.2   6.2    66.3    0.0   0.2
      인천            0.8  ...    0.7  0.0   7.9   0.7    84.2    0.1   0.0
      광주            1.5  ...    0.0  0.0   5.3   1.1    91.9    0.0   0.2
      대전            3.0  ...    0.0  0.0   9.4   1.2    88.6    0.0   0.0
      울산            0.4  ...    0.0  0.0   8.5   0.0    88.0    0.0   0.0
      경기            1.8  ...    0.4  0.4  11.4   2.6    74.8    0.0   0.4
      강원            0.0  ...    0.0  0.0   9.1   0.6    83.2    0.3   0.0
      충북            2.0  ...    0.1  0.0   6.4   0.9    91.6    0.0   0.0
      충남            1.7  ...    0.0  0.0   7.6   1.1    90.4    0.0   0.0
      전북            2.0  ...    0.3  0.2   2.9   3.2    88.4    0.0   0.0
      전남            0.8  ...    0.1  0.0   0.5   0.9    94.9    0.1   0.0
      경북            0.8  ...    1.0  0.2   3.7   0.8    86.6    0.0   0.0
      경남            1.8  ...    0.0  0.0   9.1   0.1    88.4    0.0   0.0
      제주            0.0  ...    0.0  0.0   6.0   0.2    85.8    0.0   0.0
      세종            0.8  ...    0.0  0.0  23.9   0.0    76.1    0.0   0.0
가구원수1 1인가구          1.6  ...    0.3  0.0  10.8   2.3    74.0    0.0   0.0
      2인가구          2.5  ...    0.1  0.0   6.7   0.9    86.1    0.0   0.0
      3인이상가구        1.4  ...    0.4  0.3   9.2   2.0    81.1    0.0   0.3


                  쿠팡플레이 아프리카TV   기타
전체    소계            0.2    0.3  0.0
성별    남             0.1    0.5  0.1
      여             0.3    0.1  0.0
연령    만10대미만        0.0    0.0  0.4
      만10-19세       0.0    0.1  0.1
      만20-29세       0.1    1.5  0.1
      만30-39세       0.5    0.0  0.0
      만40-49세       0.4    0.1  0.0
      만50-59세       0.0    0.1  0.0
      만60-69세       0.0    0.0  0.0
      만70세이상        0.0    0.0  0.0
월평균소득 소득없음          0.1    0.4  0.1
      50만원미만        0.5    0.0  0.0
      50-100만원미만    1.0    0.0  0.0
      100-200만원미만   0.1    0.0  0.1
      200-300만원미만   0.3    0.6  0.0
      300-400만원미만   0.2    0.2  0.0
      400-500만원미만   0.0    0.0  0.0
      500만원이상       0.0    0.1  0.0
지역    서울            0.4    0.0  0.0
      부산            0.0    0.2  0.0
      대구            0.0    0.4  0.2
      인천            0.7    0.3  0.2
      광주            0.0    0.0  0.0
      대전            0.0    0.0  0.0
      울산            0.0    0.0  0.0
      경기            0.2    0.6  0.0
      강원            0.0    0.3  0.0
      충북            0.0    0.0  0.0
      충남            0.0    0.0  0.0
      전북            0.0    0.0  0.0
      전남            0.0    2.6  0.0
      경북            0.2    0.0  0.0
      경남            0.0    0.2  0.0
      제주            2.0    0.0  1.2
      세종            0.0    0.0  0.0
가구원수1 1인가구          0.2    0.0  0.0
      2인가구          0.1    0.4  0.0
      3인이상가구        0.2    0.3  0.1

[39 rows x 29 columns]

In [9]:
# 컬럼 합치기 - 기타 컬럼

s_20=ott_s["2020"]
s_20["기타"] = s_20["기타"] + s_20["에브리온TV"] + s_20["곰TV"] + s_20["왓챠플레이"]

s_20


s_21=ott_s["2021"]
s_21["기타"] = s_21["기타"] + s_21["네이버시리즈"] + s_21["곰TV"] + s_21["아마존프라임"] 
+ s_21["왓챠플레이"] + s_21["쿠팡플레이"] + s_21["아프리카TV"]

s_21

C:\Users\LG\AppData\Local\Temp\ipykernel_7808\3191422922.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["기타"] = s_20["기타"] + s_20["에브리온TV"] + s_20["곰TV"] + s_20["왓챠플레이"]
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\3191422922.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["기타"] = s_21["기타"] + s_21["네이버시리즈"] + s_21["곰TV"] + s_21["아마존프라임"]

                      명 수   티빙  웨이브  KT_Seezn  U+모바일  네이버시리즈  곰TV  넷플릭스  \
전체    소계           8293.7  2.9  2.3       0.5    0.9     0.3  0.2   8.8
성별    남            4283.5  2.1  2.6       0.7    0.9     0.3  0.2   8.1
      여            4010.2  3.8  2.0       0.4    0.9     0.4  0.1   9.5
연령    만10대미만        174.5  1.5  0.6       1.2    0.0     0.0  0.0   6.2
      만10-19세       880.1  1.2  0.8       0.2    0.3     0.1  0.2   6.8
      만20-29세      1381.4  5.3  1.5       0.7    0.5     0.5  0.2  17.1
      만30-39세      1390.1  4.4  5.4       0.4    0.8     0.3  0.3  11.3
      만40-49세      1585.9  2.9  3.4       0.3    1.6     0.5  0.1  11.1
      만50-59세      1580.6  2.1  1.5       0.5    1.0     0.3  0.3   4.7
      만60-69세      1025.7  1.1  0.8       0.6    1.2     0.3  0.1   1.3
      만70세이상        275.5  0.6  1.1       1.4    0.3     0.0  0.0   0.4
월평균소득 소득없음         2631.2  2.2  1.4       0.4    0.7     0.4  0.1   8.4
      50만원미만        175.9  3.5  0.0       0.0    0.3     0.0  0.0   6.8
      50-100만원미만    317.8  0.9  0.9       2.7    0.3     0.0  0.0   5.8
      100-200만원미만  1094.2  1.3  2.6       0.4    1.1     0.1  0.3   9.5
      200-300만원미만  2118.0  4.1  2.3       0.4    0.9     0.2  0.1   8.9
      300-400만원미만  1326.0  4.6  3.6       0.7    1.2     0.3  0.5   7.9
      400-500만원미만   358.2  1.6  5.2       0.8    0.7     1.0  0.0  15.4
      500만원이상       272.5  2.1  4.0       0.2    1.7     1.2  0.0   9.1
지역    서울           1626.1  5.5  4.1       0.3    2.3     0.4  0.2   8.8
      부산            555.7  0.6  0.4       0.0    0.2     0.0  0.0   5.3
      대구            358.0  1.9  5.4       0.7    0.4     1.4  0.7  16.2
      인천            499.5  1.9  2.9       0.2    0.3     0.7  0.0   7.9
      광주            263.0  1.1  0.3       0.0    0.0     0.0  0.0   5.3
      대전            219.8  0.0  0.1       0.7    0.0     0.0  0.0   9.4
      울산            187.4  1.6  0.3       1.2    0.4     0.0  0.0   8.5
      경기           2226.8  4.2  3.0       0.8    1.1     0.4  0.4  11.4
      강원            207.4  0.6  2.7       3.0    0.2     0.0  0.0   9.1
      충북            279.8  0.4  0.7       0.0    0.0     0.1  0.0   6.4
      충남            305.8  0.0  0.2       0.0    0.7     0.0  0.0   7.6
      전북            292.8  3.4  1.6       0.0    0.1     0.3  0.2   2.9
      전남            279.7  0.5  0.1       0.0    0.4     0.1  0.0   0.5
      경북            318.2  4.0  1.6       0.8    1.1     1.0  0.2   3.7
      경남            501.1  0.9  0.3       0.8    0.2     0.0  0.0   9.1
      제주             84.5  1.0  3.9       0.0    0.0     0.0  0.0   6.0
      세종             88.1  0.0  0.0       0.0    0.0     0.0  0.0  23.9
가구원수1 1인가구          951.3  6.0  4.9       0.5    1.0     0.3  0.0  10.8
      2인가구         1947.3  2.9  1.4       0.4    1.1     0.1  0.0   6.7
      3인이상가구       5395.1  2.4  2.2       0.6    0.8     0.4  0.3   9.2

                   카카오TV  유튜브프리미엄  아마존프라임  왓챠플레이  쿠팡플레이  아프리카TV   기타
전체    소계             1.8     81.5     0.0    0.2    0.2     0.3  0.5
성별    남              1.6     82.6     0.0    0.1    0.1     0.5  0.6
      여              2.0     80.3     0.0    0.3    0.3     0.1  0.5
연령    만10대미만         0.0     90.2     0.0    0.0    0.0     0.0  0.4
      만10-19세        3.5     86.2     0.0    0.4    0.0     0.1  0.4
      만20-29세        1.4     70.3     0.0    0.6    0.1     1.5  0.8
      만30-39세        2.1     74.2     0.0    0.3    0.5     0.0  0.6
      만40-49세        2.0     77.4     0.0    0.1    0.4     0.1  0.6
      만50-59세        1.6     87.8     0.0    0.0    0.0     0.1  0.6
      만60-69세        0.3     94.2     0.0    0.0    0.0     0.0  0.4
      만70세이상         2.3     94.0     0.0    0.0    0.0     0.0  0.0
월평균소득 소득없음           2.1     83.3     0.0    0.4    0.1     0.4  0.6
      50만원미만         0.5     88.4     0.0    0.0    0.5     0.0  0.0
      50-100만원미만     0.3     87.5     0.0    0.5    1.0     0.0  0.0
      100-200만원미만    2.2     82.3     0.1    0.0    0.1     0.0  0.6
      200-300만원미만    1.4     80.6     0.0    0.2    0.3     0.6  0.3
      300-400만원미만    1.6     79.2     0.0    0.0    0.2     0.2  0.8
      400-500만원미만    3.3     71.7     0.0    0.2    0.0     0.0  1.0
      500만원이상        1.2     80.2     0.2    0.0    0.0     0.1  1.4
지역    서울             2.1     75.6     0.0    0.4    0.4     0.0  0.6
      부산             0.5     92.8     0.0    0.0    0.0     0.2  0.0
      대구             6.2     66.3     0.0    0.2    0.0     0.4  2.3
      인천             0.7     84.2     0.1    0.0    0.7     0.3  1.0
      광주             1.1     91.9     0.0    0.2    0.0     0.0  0.0
      대전             1.2     88.6     0.0    0.0    0.0     0.0  0.0
      울산             0.0     88.0     0.0    0.0    0.0     0.0  0.0
      경기             2.6     74.8     0.0    0.4    0.2     0.6  0.8
      강원             0.6     83.2     0.3    0.0    0.0     0.3  0.3
      충북             0.9     91.6     0.0    0.0    0.0     0.0  0.1
      충남             1.1     90.4     0.0    0.0    0.0     0.0  0.0
      전북             3.2     88.4     0.0    0.0    0.0     0.0  0.5
      전남             0.9     94.9     0.1    0.0    0.0     2.6  0.2
      경북             0.8     86.6     0.0    0.0    0.2     0.0  1.2
      경남             0.1     88.4     0.0    0.0    0.0     0.2  0.0
      제주             0.2     85.8     0.0    0.0    2.0     0.0  1.2
      세종             0.0     76.1     0.0    0.0    0.0     0.0  0.0
가구원수1 1인가구           2.3     74.0     0.0    0.0    0.2     0.0  0.3
      2인가구           0.9     86.1     0.0    0.0    0.1     0.4  0.1
      3인이상가구         2.0     81.1     0.0    0.3    0.2     0.3  0.8

In [11]:
# 필요없는 컬럼 지우기

del s_20["에브리온TV"]
del s_20["곰TV"]
del s_20["왓챠플레이"]

del s_21["네이버시리즈"] 
del s_21["곰TV"] 
del s_21["아마존프라임"] 
del s_21["왓챠플레이"]
del s_21["쿠팡플레이"]
del s_21["아프리카TV"]

KeyError: '에브리온TV'

In [12]:
#  인원수로 변환 - "명 수" 를 제외한 모든 컬럼은 % 이므로 인원수로 변환 시켜 준다.

s_20["티빙"]= round(s_20["티빙"]/100 *s_20["명 수"])
s_20["웨이브"]= round(s_20["웨이브"]/100 *s_20["명 수"])
s_20["KT_Seezn"]= round(s_20["KT_Seezn"]/100 *s_20["명 수"])
s_20["U+모바일"]= round(s_20["U+모바일"]/100 *s_20["명 수"])
s_20["네이버시리즈"]=round(s_20["네이버시리즈"]/100 *s_20["명 수"])
s_20["넷플릭스"]=round(s_20["넷플릭스"]/100 *s_20["명 수"])
s_20["카카오TV"]=round(s_20["카카오TV"]/100 *s_20["명 수"])
s_20["유튜브프리미엄"]= round(s_20["유튜브프리미엄"]/100 *s_20["명 수"])
s_20["아마존프라임"]=round(s_20["아마존프라임"]/100 *s_20["명 수"])
s_20["기타"]=round(s_20["기타"]/100 *s_20["명 수"])

C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["티빙"]= round(s_20["티빙"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["웨이브"]= round(s_20["웨이브"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["KT_Seezn"]= round(s_20["KT_Seezn"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["U+모바일"]= round(s_20["U+모바일"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["네이버시리즈"]=round(s_20["네이버시리즈"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["넷플릭스"]=round(s_20["넷플릭스"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["카카오TV"]=round(s_20["카카오TV"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["유튜브프리미엄"]= round(s_20["유튜브프리미엄"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["아마존프라임"]=round(s_20["아마존프라임"]/100 *s_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2359766938.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_20["기타"]=round(s_20["기타"]/100 *s_20["명 수"])

In [13]:
s_21["티빙"]=round(s_21["티빙"]/100 *s_21["명 수"])
s_21["웨이브"]=round(s_21["웨이브"]/100 *s_21["명 수"])
s_21["KT_Seezn"]=round(s_21["KT_Seezn"]/100 *s_21["명 수"])
s_21["U+모바일"]=round(s_21["U+모바일"]/100 *s_21["명 수"])
s_21["넷플릭스"]=round(s_21["넷플릭스"]/100 *s_21["명 수"])
s_21["카카오TV"]=round(s_21["카카오TV"]/100 *s_21["명 수"])
s_21["유튜브프리미엄"]=round(s_21["유튜브프리미엄"]/100 *s_21["명 수"])
s_21["기타"]=round(s_21["기타"]/100 *s_21["명 수"])

C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["티빙"]=round(s_21["티빙"]/100 *s_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["웨이브"]=round(s_21["웨이브"]/100 *s_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["KT_Seezn"]=round(s_21["KT_Seezn"]/100 *s_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["U+모바일"]=round(s_21["U+모바일"]/100 *s_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["넷플릭스"]=round(s_21["넷플릭스"]/100 *s_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["카카오TV"]=round(s_21["카카오TV"]/100 *s_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["유튜브프리미엄"]=round(s_21["유튜브프리미엄"]/100 *s_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\2695511137.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_21["기타"]=round(s_21["기타"]/100 *s_21["명 수"])

In [14]:
s_20

                    명 수     티빙    웨이브  KT_Seezn  U+모바일  네이버시리즈   넷플릭스  카카오TV  \
전체    소계           7434  327.0  297.0      74.0   97.0    52.0  528.0  119.0
성별    남            3872  151.0  151.0      43.0   50.0    27.0  252.0   62.0
      여            3562  175.0  142.0      28.0   46.0    21.0  278.0   61.0
연령    만10대미만        173    2.0    0.0       5.0    0.0     0.0    2.0    0.0
      만10-19세       825   31.0    8.0       4.0    4.0     3.0   38.0   11.0
      만20-29세      1378   87.0   52.0      10.0   12.0     8.0  181.0   26.0
      만30-39세      1420   61.0  115.0       9.0   21.0    10.0  135.0   17.0
      만40-49세      1481   77.0   64.0      18.0   37.0    13.0  114.0   15.0
      만50-59세      1373   52.0   27.0      12.0   11.0    15.0   52.0   29.0
      만60-69세       666   15.0   25.0      13.0    7.0     3.0    8.0   18.0
      만70세이상        119    1.0    5.0       3.0    2.0     0.0    0.0    4.0
월평균소득 소득없음         2477  116.0   57.0      20.0   22.0    15.0  136.0   25.0
      50만원미만        138   13.0    4.0       3.0    3.0     0.0    9.0    1.0
      50-100만원미만    222    5.0   10.0       7.0    8.0     2.0   18.0    3.0
      100-200만원미만  1120   55.0   53.0      10.0    9.0     2.0   58.0   46.0
      200-300만원미만  1961   82.0   98.0      12.0   18.0    10.0  169.0   25.0
      300-400만원미만  1026   37.0   57.0      15.0   26.0    12.0   97.0   13.0
      400-500만원미만   266   13.0    3.0       3.0    6.0     5.0   31.0    3.0
      500만원이상       224    4.0   16.0       4.0    3.0     4.0   11.0    4.0
지역    서울           1482   65.0   92.0      18.0   43.0     9.0  182.0   33.0
      부산            524    1.0    4.0       0.0    4.0     6.0   27.0    6.0
      대구            335   13.0   10.0       5.0    4.0     5.0   32.0    6.0
      인천            452    9.0   16.0       2.0    1.0     6.0   23.0    4.0
      광주            248   14.0    1.0       0.0    0.0     0.0   11.0    4.0
      대전            213    3.0    9.0       0.0    0.0     0.0   13.0    6.0
      울산            176    0.0    3.0       4.0    2.0     2.0    2.0    1.0
      경기           1907  181.0   93.0      27.0   29.0    15.0  126.0   34.0
      강원            181    1.0    3.0       5.0    3.0     0.0   12.0    0.0
      충북            264    6.0    3.0       0.0    0.0     0.0   20.0    5.0
      충남            265    8.0   19.0       1.0    2.0     2.0    5.0    5.0
      전북            262    6.0    1.0       0.0    1.0     0.0   25.0    5.0
      전남            245   12.0    2.0       0.0    0.0     1.0    9.0    2.0
      경북            291    2.0   32.0       3.0    3.0     3.0   13.0    2.0
      경남            427    2.0    6.0       4.0    2.0     2.0   18.0    8.0
      제주             83    0.0    2.0       5.0    1.0     1.0    3.0    0.0
      세종             79    3.0    0.0       0.0    0.0     0.0    6.0    1.0
가구원수1 1인가구          822   12.0   69.0       4.0    7.0     0.0   79.0   13.0
      2인가구         1586   78.0   57.0       8.0   10.0    13.0  103.0   40.0
      3인이상가구       5027  236.0  171.0      60.0   80.0    40.0  347.0   70.0

                   유튜브프리미엄  아마존프라임    기타
전체    소계            5880.0    37.0  22.0
성별    남             3105.0    19.0   8.0
      여             2775.0    21.0  14.0
연령    만10대미만         165.0     0.0   0.0
      만10-19세        722.0     2.0   2.0
      만20-29세        989.0     6.0   4.0
      만30-39세       1037.0     9.0   7.0
      만40-49세       1130.0     7.0   7.0
      만50-59세       1168.0     4.0   1.0
      만60-69세        569.0     9.0   0.0
      만70세이상         102.0     1.0   0.0
월평균소득 소득없음          2063.0    15.0   5.0
      50만원미만         101.0     3.0   1.0
      50-100만원미만     169.0     1.0   0.0
      100-200만원미만    878.0     2.0   7.0
      200-300만원미만   1532.0    12.0   4.0
      300-400만원미만    757.0     5.0   5.0
      400-500만원미만    202.0     0.0   0.0
      500만원이상        177.0     1.0   1.0
지역    서울            1031.0     1.0   6.0
      부산             474.0     3.0   1.0
      대구             256.0     0.0   3.0
      인천             391.0     0.0   1.0
      광주             214.0     4.0   0.0
      대전             177.0     2.0   3.0
      울산             162.0     1.0   0.0
      경기            1394.0     4.0   2.0
      강원             157.0     1.0   0.0
      충북             223.0     2.0   4.0
      충남             223.0     0.0   0.0
      전북             223.0     0.0   1.0
      전남             204.0    15.0   0.0
      경북             230.0     1.0   1.0
      경남             380.0     3.0   1.0
      제주              70.0     0.0   0.0
      세종              69.0     0.0   0.0
가구원수1 1인가구           635.0     2.0   0.0
      2인가구          1264.0    14.0   0.0
      3인이상가구        3981.0    20.0  20.0

In [15]:
s_21

                      명 수     티빙    웨이브  KT_Seezn  U+모바일   넷플릭스  카카오TV  \
전체    소계           8293.7  241.0  191.0      41.0   75.0  730.0  149.0
성별    남            4283.5   90.0  111.0      30.0   39.0  347.0   69.0
      여            4010.2  152.0   80.0      16.0   36.0  381.0   80.0
연령    만10대미만        174.5    3.0    1.0       2.0    0.0   11.0    0.0
      만10-19세       880.1   11.0    7.0       2.0    3.0   60.0   31.0
      만20-29세      1381.4   73.0   21.0      10.0    7.0  236.0   19.0
      만30-39세      1390.1   61.0   75.0       6.0   11.0  157.0   29.0
      만40-49세      1585.9   46.0   54.0       5.0   25.0  176.0   32.0
      만50-59세      1580.6   33.0   24.0       8.0   16.0   74.0   25.0
      만60-69세      1025.7   11.0    8.0       6.0   12.0   13.0    3.0
      만70세이상        275.5    2.0    3.0       4.0    1.0    1.0    6.0
월평균소득 소득없음         2631.2   58.0   37.0      11.0   18.0  221.0   55.0
      50만원미만        175.9    6.0    0.0       0.0    1.0   12.0    1.0
      50-100만원미만    317.8    3.0    3.0       9.0    1.0   18.0    1.0
      100-200만원미만  1094.2   14.0   28.0       4.0   12.0  104.0   24.0
      200-300만원미만  2118.0   87.0   49.0       8.0   19.0  189.0   30.0
      300-400만원미만  1326.0   61.0   48.0       9.0   16.0  105.0   21.0
      400-500만원미만   358.2    6.0   19.0       3.0    3.0   55.0   12.0
      500만원이상       272.5    6.0   11.0       1.0    5.0   25.0    3.0
지역    서울           1626.1   89.0   67.0       5.0   37.0  143.0   34.0
      부산            555.7    3.0    2.0       0.0    1.0   29.0    3.0
      대구            358.0    7.0   19.0       3.0    1.0   58.0   22.0
      인천            499.5    9.0   14.0       1.0    1.0   39.0    3.0
      광주            263.0    3.0    1.0       0.0    0.0   14.0    3.0
      대전            219.8    0.0    0.0       2.0    0.0   21.0    3.0
      울산            187.4    3.0    1.0       2.0    1.0   16.0    0.0
      경기           2226.8   94.0   67.0      18.0   24.0  254.0   58.0
      강원            207.4    1.0    6.0       6.0    0.0   19.0    1.0
      충북            279.8    1.0    2.0       0.0    0.0   18.0    3.0
      충남            305.8    0.0    1.0       0.0    2.0   23.0    3.0
      전북            292.8   10.0    5.0       0.0    0.0    8.0    9.0
      전남            279.7    1.0    0.0       0.0    1.0    1.0    3.0
      경북            318.2   13.0    5.0       3.0    4.0   12.0    3.0
      경남            501.1    5.0    2.0       4.0    1.0   46.0    1.0
      제주             84.5    1.0    3.0       0.0    0.0    5.0    0.0
      세종             88.1    0.0    0.0       0.0    0.0   21.0    0.0
가구원수1 1인가구          951.3   57.0   47.0       5.0   10.0  103.0   22.0
      2인가구         1947.3   56.0   27.0       8.0   21.0  130.0   18.0
      3인이상가구       5395.1  129.0  119.0      32.0   43.0  496.0  108.0

                   유튜브프리미엄    기타
전체    소계            6759.0  41.0
성별    남             3538.0  26.0
      여             3220.0  20.0
연령    만10대미만         157.0   1.0
      만10-19세        759.0   4.0
      만20-29세        971.0  11.0
      만30-39세       1031.0   8.0
      만40-49세       1227.0  10.0
      만50-59세       1388.0   9.0
      만60-69세        966.0   4.0
      만70세이상         259.0   0.0
월평균소득 소득없음          2192.0  16.0
      50만원미만         155.0   0.0
      50-100만원미만     278.0   0.0
      100-200만원미만    901.0   7.0
      200-300만원미만   1707.0   6.0
      300-400만원미만   1050.0  11.0
      400-500만원미만    257.0   4.0
      500만원이상        219.0   4.0
지역    서울            1229.0  10.0
      부산             516.0   0.0
      대구             237.0   8.0
      인천             421.0   5.0
      광주             242.0   0.0
      대전             195.0   0.0
      울산             165.0   0.0
      경기            1666.0  18.0
      강원             173.0   1.0
      충북             256.0   0.0
      충남             276.0   0.0
      전북             259.0   1.0
      전남             265.0   1.0
      경북             276.0   4.0
      경남             443.0   0.0
      제주              73.0   1.0
      세종              67.0   0.0
가구원수1 1인가구           704.0   3.0
      2인가구          1677.0   2.0
      3인이상가구        4375.0  43.0

In [16]:
# 연도별 증감율....?

# 컬럼이 다름.... 
(s_21["티빙"] - s_20["티빙"])/ s_20["티빙"] *100
#(s_21["넷플릭스"] - s_20["넷플릭스"])/ s_20["넷플릭스"] *100

전체     소계             -26.299694
성별     남              -40.397351
       여              -13.142857
연령     만10대미만          50.000000
       만10-19세        -64.516129
       만20-29세        -16.091954
       만30-39세          0.000000
       만40-49세        -40.259740
       만50-59세        -36.538462
       만60-69세        -26.666667
       만70세이상         100.000000
월평균소득  소득없음           -50.000000
       50만원미만         -53.846154
       50-100만원미만     -40.000000
       100-200만원미만    -74.545455
       200-300만원미만      6.097561
       300-400만원미만     64.864865
       400-500만원미만    -53.846154
       500만원이상         50.000000
지역     서울              36.923077
       부산             200.000000
       대구             -46.153846
       인천               0.000000
       광주             -78.571429
       대전            -100.000000
       울산                    inf
       경기             -48.066298
       강원               0.000000
       충북             -83.333333
       충남            -100.000000
       전북              66.666667
       전남             -91.666667
       경북             550.000000
       경남             150.000000
       제주                    inf
       세종            -100.000000
가구원수1  1인가구           375.000000
       2인가구           -28.205128
       3인이상가구         -45.338983
Name: 티빙, dtype: float64

In [ ]:
# 함수화

In [17]:
#concat으로 2021, 2020 합치기
ott_service_20_21=pd.concat([s_20,s_21], axis=1) 
ott_service_20_21

# 중간 저장
#ott_service_20_21.to_csv("../project_data_raw/.csv", index = False)

                    명 수     티빙    웨이브  KT_Seezn  U+모바일  네이버시리즈   넷플릭스  카카오TV  \
전체    소계           7434  327.0  297.0      74.0   97.0    52.0  528.0  119.0
성별    남            3872  151.0  151.0      43.0   50.0    27.0  252.0   62.0
      여            3562  175.0  142.0      28.0   46.0    21.0  278.0   61.0
연령    만10대미만        173    2.0    0.0       5.0    0.0     0.0    2.0    0.0
      만10-19세       825   31.0    8.0       4.0    4.0     3.0   38.0   11.0
      만20-29세      1378   87.0   52.0      10.0   12.0     8.0  181.0   26.0
      만30-39세      1420   61.0  115.0       9.0   21.0    10.0  135.0   17.0
      만40-49세      1481   77.0   64.0      18.0   37.0    13.0  114.0   15.0
      만50-59세      1373   52.0   27.0      12.0   11.0    15.0   52.0   29.0
      만60-69세       666   15.0   25.0      13.0    7.0     3.0    8.0   18.0
      만70세이상        119    1.0    5.0       3.0    2.0     0.0    0.0    4.0
월평균소득 소득없음         2477  116.0   57.0      20.0   22.0    15.0  136.0   25.0
      50만원미만        138   13.0    4.0       3.0    3.0     0.0    9.0    1.0
      50-100만원미만    222    5.0   10.0       7.0    8.0     2.0   18.0    3.0
      100-200만원미만  1120   55.0   53.0      10.0    9.0     2.0   58.0   46.0
      200-300만원미만  1961   82.0   98.0      12.0   18.0    10.0  169.0   25.0
      300-400만원미만  1026   37.0   57.0      15.0   26.0    12.0   97.0   13.0
      400-500만원미만   266   13.0    3.0       3.0    6.0     5.0   31.0    3.0
      500만원이상       224    4.0   16.0       4.0    3.0     4.0   11.0    4.0
지역    서울           1482   65.0   92.0      18.0   43.0     9.0  182.0   33.0
      부산            524    1.0    4.0       0.0    4.0     6.0   27.0    6.0
      대구            335   13.0   10.0       5.0    4.0     5.0   32.0    6.0
      인천            452    9.0   16.0       2.0    1.0     6.0   23.0    4.0
      광주            248   14.0    1.0       0.0    0.0     0.0   11.0    4.0
      대전            213    3.0    9.0       0.0    0.0     0.0   13.0    6.0
      울산            176    0.0    3.0       4.0    2.0     2.0    2.0    1.0
      경기           1907  181.0   93.0      27.0   29.0    15.0  126.0   34.0
      강원            181    1.0    3.0       5.0    3.0     0.0   12.0    0.0
      충북            264    6.0    3.0       0.0    0.0     0.0   20.0    5.0
      충남            265    8.0   19.0       1.0    2.0     2.0    5.0    5.0
      전북            262    6.0    1.0       0.0    1.0     0.0   25.0    5.0
      전남            245   12.0    2.0       0.0    0.0     1.0    9.0    2.0
      경북            291    2.0   32.0       3.0    3.0     3.0   13.0    2.0
      경남            427    2.0    6.0       4.0    2.0     2.0   18.0    8.0
      제주             83    0.0    2.0       5.0    1.0     1.0    3.0    0.0
      세종             79    3.0    0.0       0.0    0.0     0.0    6.0    1.0
가구원수1 1인가구          822   12.0   69.0       4.0    7.0     0.0   79.0   13.0
      2인가구         1586   78.0   57.0       8.0   10.0    13.0  103.0   40.0
      3인이상가구       5027  236.0  171.0      60.0   80.0    40.0  347.0   70.0

                   유튜브프리미엄  아마존프라임    기타     명 수     티빙    웨이브  KT_Seezn  \
전체    소계            5880.0    37.0  22.0  8293.7  241.0  191.0      41.0
성별    남             3105.0    19.0   8.0  4283.5   90.0  111.0      30.0
      여             2775.0    21.0  14.0  4010.2  152.0   80.0      16.0
연령    만10대미만         165.0     0.0   0.0   174.5    3.0    1.0       2.0
      만10-19세        722.0     2.0   2.0   880.1   11.0    7.0       2.0
      만20-29세        989.0     6.0   4.0  1381.4   73.0   21.0      10.0
      만30-39세       1037.0     9.0   7.0  1390.1   61.0   75.0       6.0
      만40-49세       1130.0     7.0   7.0  1585.9   46.0   54.0       5.0
      만50-59세       1168.0     4.0   1.0  1580.6   33.0   24.0       8.0
      만60-69세        569.0     9.0   0.0  1025.7   11.0    8.0       6.0
      만70세이상         102.0     1.0   0.0   275.5    2.0    3.0       4.0
월평균소득 소득없음          2063.0    15.0   5.0  2631.2   58.0   37.0      11.0
      50만원미만         101.0     3.0   1.0   175.9    6.0    0.0       0.0
      50-100만원미만     169.0     1.0   0.0   317.8    3.0    3.0       9.0
      100-200만원미만    878.0     2.0   7.0  1094.2   14.0   28.0       4.0
      200-300만원미만   1532.0    12.0   4.0  2118.0   87.0   49.0       8.0
      300-400만원미만    757.0     5.0   5.0  1326.0   61.0   48.0       9.0
      400-500만원미만    202.0     0.0   0.0   358.2    6.0   19.0       3.0
      500만원이상        177.0     1.0   1.0   272.5    6.0   11.0       1.0
지역    서울            1031.0     1.0   6.0  1626.1   89.0   67.0       5.0
      부산             474.0     3.0   1.0   555.7    3.0    2.0       0.0
      대구             256.0     0.0   3.0   358.0    7.0   19.0       3.0
      인천             391.0     0.0   1.0   499.5    9.0   14.0       1.0
      광주             214.0     4.0   0.0   263.0    3.0    1.0       0.0
      대전             177.0     2.0   3.0   219.8    0.0    0.0       2.0
      울산             162.0     1.0   0.0   187.4    3.0    1.0       2.0
      경기            1394.0     4.0   2.0  2226.8   94.0   67.0      18.0
      강원             157.0     1.0   0.0   207.4    1.0    6.0       6.0
      충북             223.0     2.0   4.0   279.8    1.0    2.0       0.0
      충남             223.0     0.0   0.0   305.8    0.0    1.0       0.0
      전북             223.0     0.0   1.0   292.8   10.0    5.0       0.0
      전남             204.0    15.0   0.0   279.7    1.0    0.0       0.0
      경북             230.0     1.0   1.0   318.2   13.0    5.0       3.0
      경남             380.0     3.0   1.0   501.1    5.0    2.0       4.0
      제주              70.0     0.0   0.0    84.5    1.0    3.0       0.0
      세종              69.0     0.0   0.0    88.1    0.0    0.0       0.0
가구원수1 1인가구           635.0     2.0   0.0   951.3   57.0   47.0       5.0
      2인가구          1264.0    14.0   0.0  1947.3   56.0   27.0       8.0
      3인이상가구        3981.0    20.0  20.0  5395.1  129.0  119.0      32.0

                   U+모바일   넷플릭스  카카오TV  유튜브프리미엄    기타
전체    소계            75.0  730.0  149.0   6759.0  41.0
성별    남             39.0  347.0   69.0   3538.0  26.0
      여             36.0  381.0   80.0   3220.0  20.0
연령    만10대미만         0.0   11.0    0.0    157.0   1.0
      만10-19세        3.0   60.0   31.0    759.0   4.0
      만20-29세        7.0  236.0   19.0    971.0  11.0
      만30-39세       11.0  157.0   29.0   1031.0   8.0
      만40-49세       25.0  176.0   32.0   1227.0  10.0
      만50-59세       16.0   74.0   25.0   1388.0   9.0
      만60-69세       12.0   13.0    3.0    966.0   4.0
      만70세이상         1.0    1.0    6.0    259.0   0.0
월평균소득 소득없음          18.0  221.0   55.0   2192.0  16.0
      50만원미만         1.0   12.0    1.0    155.0   0.0
      50-100만원미만     1.0   18.0    1.0    278.0   0.0
      100-200만원미만   12.0  104.0   24.0    901.0   7.0
      200-300만원미만   19.0  189.0   30.0   1707.0   6.0
      300-400만원미만   16.0  105.0   21.0   1050.0  11.0
      400-500만원미만    3.0   55.0   12.0    257.0   4.0
      500만원이상        5.0   25.0    3.0    219.0   4.0
지역    서울            37.0  143.0   34.0   1229.0  10.0
      부산             1.0   29.0    3.0    516.0   0.0
      대구             1.0   58.0   22.0    237.0   8.0
      인천             1.0   39.0    3.0    421.0   5.0
      광주             0.0   14.0    3.0    242.0   0.0
      대전             0.0   21.0    3.0    195.0   0.0
      울산             1.0   16.0    0.0    165.0   0.0
      경기            24.0  254.0   58.0   1666.0  18.0
      강원             0.0   19.0    1.0    173.0   1.0
      충북             0.0   18.0    3.0    256.0   0.0
      충남             2.0   23.0    3.0    276.0   0.0
      전북             0.0    8.0    9.0    259.0   1.0
      전남             1.0    1.0    3.0    265.0   1.0
      경북             4.0   12.0    3.0    276.0   4.0
      경남             1.0   46.0    1.0    443.0   0.0
      제주             0.0    5.0    0.0     73.0   1.0
      세종             0.0   21.0    0.0     67.0   0.0
가구원수1 1인가구          10.0  103.0   22.0    704.0   3.0
      2인가구          21.0  130.0   18.0   1677.0   2.0
      3인이상가구        43.0  496.0  108.0   4375.0  43.0

## 2. 가장 많이 이용하는 ott 서비스 이용 매체 1순위 

### 성별/나이별/소득별/지역/가구원수1

### 1)  데이터 전처리

In [18]:
# 엑셀 파일 불러오기

ott_m = pd.read_excel("가장_많이_이용하는_OTT_서비스의_주_이용_매체_1순위.xlsx",  header=[0,1], index_col=[0,1])
ott_m

C:\Users\LG\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

구분별(2)               2020                                              \
구분별(2)            사례수 (명) 스마트폰 (%) 태블릿PC (%) 데스크톱 컴퓨터 (%) 노트북 컴퓨터 (%)
전체    소계             7434     96.4       0.9          1.0         0.8
성별    남              3872     96.0       0.9          1.3         0.9
      여              3562     96.9       0.9          0.6         0.7
연령    만10대미만          173     85.7       9.0          0.0         2.6
      만10-19세         825     93.3       1.4          2.0         1.5
      만20-29세        1378     94.9       1.9          1.2         1.9
      만30-39세        1420     98.8       0.1          1.0         0.0
      만40-49세        1481     97.6       0.3          0.5         0.4
      만50-59세        1373     97.1       0.2          1.0         0.4
      만60-69세         666     97.3       0.7          0.3         0.5
      만70세이상          119     98.2       0.0          1.1         0.0
월평균소득 소득없음           2477     94.7       1.6          1.1         1.2
      50만원미만          138     96.2       2.2          0.3         0.9
      50-100만원미만      222     98.4       0.0          0.3         1.4
      100-200만원미만    1120     97.8       0.8          0.5         0.1
      200-300만원미만    1961     97.4       0.4          1.0         0.6
      300-400만원미만    1026     97.7       0.3          1.0         0.4
      400-500만원미만     266     95.0       1.1          1.3         0.6
      500만원이상         224     94.7       0.0          1.3         2.7
지역    서울             1482     96.4       0.9          0.7         0.9
      부산              524     99.3       0.0          0.0         0.3
      대구              335     89.3       4.0          2.7         2.4
      인천              452     96.2       1.6          0.7         0.7
      광주              248     97.9       0.6          0.9         0.5
      대전              213     99.5       0.5          0.0         0.0
      울산              176     97.5       0.0          2.0         0.1
      경기             1907     95.6       0.8          1.5         0.7
      강원              181     87.9       4.7          0.3         3.8
      충북              264     98.4       0.0          1.2         0.4
      충남              265     97.9       0.0          1.5         0.0
      전북              262     99.2       0.0          0.3         0.0
      전남              245    100.0       0.0          0.0         0.0
      경북              291     93.0       1.6          1.8         2.7
      경남              427     99.8       0.0          0.0         0.0
      제주               83     95.6       0.3          1.7         1.2
      세종               79    100.0       0.0          0.0         0.0
가구원수1 1인가구            822     98.6       0.0          0.6         0.8
      2인가구           1586     97.9       0.6          0.3         0.8
      3인이상가구         5027     95.6       1.1          1.2         0.8

구분별(2)                          2021                                  \
구분별(2)            TV 수상기 (%) 사례수 (명) 스마트폰 (%) 태블릿PC (%) 데스크톱 컴퓨터 (%)
전체    소계                 0.9  8293.7     92.8       2.6          0.8
성별    남                  0.9  4283.5     93.8       2.3          1.1
      여                  1.0  4010.2     91.8       3.0          0.5
연령    만10대미만             2.6   174.5     61.5      28.8          0.5
      만10-19세            1.7   880.1     87.1       5.2          2.7
      만20-29세            0.1  1381.4     90.0       4.6          1.1
      만30-39세            0.2  1390.1     95.4       2.5          0.1
      만40-49세            1.3  1585.9     93.3       0.9          0.9
      만50-59세            1.4  1580.6     95.4       0.4          0.8
      만60-69세            1.1  1025.7     97.6       0.3          0.2
      만70세이상             0.7   275.5     97.3       0.1          0.3
월평균소득 소득없음               1.4  2631.2     89.0       4.9          1.4
      50만원미만             0.3   175.9     94.1       3.0          0.4
      50-100만원미만         0.0   317.8     94.9       1.2          2.8
      100-200만원미만        0.7  1094.2     95.4       1.3          0.3
      200-300만원미만        0.6  2118.0     94.9       1.1          0.3
      300-400만원미만        0.5  1326.0     95.2       2.3          0.2
      400-500만원미만        1.9   358.2     90.9       2.4          0.8
      500만원이상            1.3   272.5     90.6       1.5          2.5
지역    서울                 1.1  1626.1     93.3       2.4          0.4
      부산                 0.4   555.7     99.2       0.0          0.3
      대구                 1.5   358.0     84.2       7.6          1.4
      인천                 0.8   499.5     91.3       2.9          1.5
      광주                 0.1   263.0     95.1       1.6          0.0
      대전                 0.0   219.8     92.5       0.4          0.2
      울산                 0.4   187.4     98.6       0.3          0.1
      경기                 1.4  2226.8     91.4       3.5          1.4
      강원                 3.3   207.4     91.3       1.9          0.7
      충북                 0.0   279.8     86.8       7.4          0.0
      충남                 0.5   305.8     98.4       0.3          0.0
      전북                 0.5   292.8     94.5       0.0          0.0
      전남                 0.0   279.7     91.9       4.6          0.6
      경북                 1.0   318.2     94.4       2.3          1.0
      경남                 0.2   501.1     97.8       0.0          0.0
      제주                 1.3    84.5     93.6       2.8          1.6
      세종                 0.0    88.1     70.2       5.5         12.0
가구원수1 1인가구               0.0   951.3     94.4       1.2          0.6
      2인가구               0.4  1947.3     96.2       0.7          0.4
      3인이상가구             1.2  5395.1     91.3       3.6          1.1

구분별(2)
구분별(2)            노트북 컴퓨터 (%) TV 수상기 (%)
전체    소계                  1.2        2.5
성별    남                   1.0        1.8
      여                   1.4        3.3
연령    만10대미만              0.9        8.4
      만10-19세             3.5        1.5
      만20-29세             3.0        1.4
      만30-39세             0.4        1.6
      만40-49세             0.5        4.5
      만50-59세             0.6        2.9
      만60-69세             0.4        1.5
      만70세이상              0.0        2.2
월평균소득 소득없음                1.9        2.9
      50만원미만              0.4        2.0
      50-100만원미만          0.0        1.1
      100-200만원미만         0.4        2.5
      200-300만원미만         1.3        2.3
      300-400만원미만         0.7        1.6
      400-500만원미만         0.8        5.1
      500만원이상             2.0        3.4
지역    서울                  0.9        3.0
      부산                  0.0        0.4
      대구                  2.9        3.9
      인천                  2.5        1.8
      광주                  0.0        3.2
      대전                  4.1        2.8
      울산                  0.0        1.1
      경기                  1.0        2.7
      강원                  0.3        5.8
      충북                  5.8        0.0
      충남                  0.3        0.9
      전북                  0.8        4.7
      전남                  0.0        2.9
      경북                  0.3        2.0
      경남                  0.0        2.2
      제주                  1.2        0.8
      세종                  8.8        3.6
가구원수1 1인가구                1.0        2.9
      2인가구                0.7        2.1
      3인이상가구              1.4        2.6

In [19]:
# 컬럼 명 변경

ott_m.columns =[["2020","2020","2020","2020","2020","2020", "2021","2021","2021","2021","2021","2021"],
              ["명 수","스마트폰", "태블릿PC", "데스크톱컴퓨터", "노트북컴퓨터", "TV", "명 수","스마트폰", "태블릿PC", "데스크톱컴퓨터", "노트북컴퓨터", "TV"]]

In [20]:
ott_m.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 39 entries, ('전체', '소계') to ('가구원수1', '3인이상가구')
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (2020, 명 수)      39 non-null     int64
 1   (2020, 스마트폰)     39 non-null     float64
 2   (2020, 태블릿PC)    39 non-null     float64
 3   (2020, 데스크톱컴퓨터)  39 non-null     float64
 4   (2020, 노트북컴퓨터)   39 non-null     float64
 5   (2020, TV)       39 non-null     float64
 6   (2021, 명 수)      39 non-null     float64
 7   (2021, 스마트폰)     39 non-null     float64
 8   (2021, 태블릿PC)    39 non-null     float64
 9   (2021, 데스크톱컴퓨터)  39 non-null     float64
 10  (2021, 노트북컴퓨터)   39 non-null     float64
 11  (2021, TV)       39 non-null     float64
dtypes: float64(11), int64(1)
memory usage: 5.3+ KB

In [21]:
#  인원수로 변환 - "명 수" 를 제외한 모든 컬럼은 % 이므로 인원수로 변환 시켜 준다.

m_20=ott_m["2020"]

m_20["스마트폰"]=round(m_20["스마트폰"]/100 *m_20["명 수"])
m_20["태블릿PC"]=round(m_20["태블릿PC"]/100 *m_20["명 수"])
m_20["데스크톱컴퓨터"]=round(m_20["데스크톱컴퓨터"]/100 *m_20["명 수"])
m_20["노트북컴퓨터"]=round(m_20["노트북컴퓨터"]/100 *m_20["명 수"])
m_20["TV"]=round(m_20["TV"]/100 *m_20["명 수"])

m_20

C:\Users\LG\AppData\Local\Temp\ipykernel_7808\1981912577.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_20["스마트폰"]=round(m_20["스마트폰"]/100 *m_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\1981912577.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_20["태블릿PC"]=round(m_20["태블릿PC"]/100 *m_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\1981912577.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_20["데스크톱컴퓨터"]=round(m_20["데스크톱컴퓨터"]/100 *m_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\1981912577.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_20["노트북컴퓨터"]=round(m_20["노트북컴퓨터"]/100 *m_20["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\1981912577.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_20["TV"]=round(m_20["TV"]/100 *m_20["명 수"])

                    명 수    스마트폰  태블릿PC  데스크톱컴퓨터  노트북컴퓨터    TV
전체    소계           7434  7166.0   67.0     74.0    59.0  67.0
성별    남            3872  3717.0   35.0     50.0    35.0  35.0
      여            3562  3452.0   32.0     21.0    25.0  36.0
연령    만10대미만        173   148.0   16.0      0.0     4.0   4.0
      만10-19세       825   770.0   12.0     16.0    12.0  14.0
      만20-29세      1378  1308.0   26.0     17.0    26.0   1.0
      만30-39세      1420  1403.0    1.0     14.0     0.0   3.0
      만40-49세      1481  1445.0    4.0      7.0     6.0  19.0
      만50-59세      1373  1333.0    3.0     14.0     5.0  19.0
      만60-69세       666   648.0    5.0      2.0     3.0   7.0
      만70세이상        119   117.0    0.0      1.0     0.0   1.0
월평균소득 소득없음         2477  2346.0   40.0     27.0    30.0  35.0
      50만원미만        138   133.0    3.0      0.0     1.0   0.0
      50-100만원미만    222   218.0    0.0      1.0     3.0   0.0
      100-200만원미만  1120  1095.0    9.0      6.0     1.0   8.0
      200-300만원미만  1961  1910.0    8.0     20.0    12.0  12.0
      300-400만원미만  1026  1002.0    3.0     10.0     4.0   5.0
      400-500만원미만   266   253.0    3.0      3.0     2.0   5.0
      500만원이상       224   212.0    0.0      3.0     6.0   3.0
지역    서울           1482  1429.0   13.0     10.0    13.0  16.0
      부산            524   520.0    0.0      0.0     2.0   2.0
      대구            335   299.0   13.0      9.0     8.0   5.0
      인천            452   435.0    7.0      3.0     3.0   4.0
      광주            248   243.0    1.0      2.0     1.0   0.0
      대전            213   212.0    1.0      0.0     0.0   0.0
      울산            176   172.0    0.0      4.0     0.0   1.0
      경기           1907  1823.0   15.0     29.0    13.0  27.0
      강원            181   159.0    9.0      1.0     7.0   6.0
      충북            264   260.0    0.0      3.0     1.0   0.0
      충남            265   259.0    0.0      4.0     0.0   1.0
      전북            262   260.0    0.0      1.0     0.0   1.0
      전남            245   245.0    0.0      0.0     0.0   0.0
      경북            291   271.0    5.0      5.0     8.0   3.0
      경남            427   426.0    0.0      0.0     0.0   1.0
      제주             83    79.0    0.0      1.0     1.0   1.0
      세종             79    79.0    0.0      0.0     0.0   0.0
가구원수1 1인가구          822   810.0    0.0      5.0     7.0   0.0
      2인가구         1586  1553.0   10.0      5.0    13.0   6.0
      3인이상가구       5027  4806.0   55.0     60.0    40.0  60.0

In [22]:
m_21=ott_m["2021"]

m_21["스마트폰"]=round(m_21["스마트폰"]/100 *m_21["명 수"])
m_21["태블릿PC"]=round(m_21["태블릿PC"]/100 *m_21["명 수"])
m_21["데스크톱컴퓨터"]=round(m_21["데스크톱컴퓨터"]/100 *m_21["명 수"])
m_21["노트북컴퓨터"]=round(m_21["노트북컴퓨터"]/100 *m_21["명 수"])
m_21["TV"]=round(m_21["TV"]/100 *m_21["명 수"])

m_21

C:\Users\LG\AppData\Local\Temp\ipykernel_7808\238125964.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_21["스마트폰"]=round(m_21["스마트폰"]/100 *m_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\238125964.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_21["태블릿PC"]=round(m_21["태블릿PC"]/100 *m_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\238125964.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_21["데스크톱컴퓨터"]=round(m_21["데스크톱컴퓨터"]/100 *m_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\238125964.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_21["노트북컴퓨터"]=round(m_21["노트북컴퓨터"]/100 *m_21["명 수"])
C:\Users\LG\AppData\Local\Temp\ipykernel_7808\238125964.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_21["TV"]=round(m_21["TV"]/100 *m_21["명 수"])

                      명 수    스마트폰  태블릿PC  데스크톱컴퓨터  노트북컴퓨터     TV
전체    소계           8293.7  7697.0  216.0     66.0   100.0  207.0
성별    남            4283.5  4018.0   99.0     47.0    43.0   77.0
      여            4010.2  3681.0  120.0     20.0    56.0  132.0
연령    만10대미만        174.5   107.0   50.0      1.0     2.0   15.0
      만10-19세       880.1   767.0   46.0     24.0    31.0   13.0
      만20-29세      1381.4  1243.0   64.0     15.0    41.0   19.0
      만30-39세      1390.1  1326.0   35.0      1.0     6.0   22.0
      만40-49세      1585.9  1480.0   14.0     14.0     8.0   71.0
      만50-59세      1580.6  1508.0    6.0     13.0     9.0   46.0
      만60-69세      1025.7  1001.0    3.0      2.0     4.0   15.0
      만70세이상        275.5   268.0    0.0      1.0     0.0    6.0
월평균소득 소득없음         2631.2  2342.0  129.0     37.0    50.0   76.0
      50만원미만        175.9   166.0    5.0      1.0     1.0    4.0
      50-100만원미만    317.8   302.0    4.0      9.0     0.0    3.0
      100-200만원미만  1094.2  1044.0   14.0      3.0     4.0   27.0
      200-300만원미만  2118.0  2010.0   23.0      6.0    28.0   49.0
      300-400만원미만  1326.0  1262.0   30.0      3.0     9.0   21.0
      400-500만원미만   358.2   326.0    9.0      3.0     3.0   18.0
      500만원이상       272.5   247.0    4.0      7.0     5.0    9.0
지역    서울           1626.1  1517.0   39.0      7.0    15.0   49.0
      부산            555.7   551.0    0.0      2.0     0.0    2.0
      대구            358.0   301.0   27.0      5.0    10.0   14.0
      인천            499.5   456.0   14.0      7.0    12.0    9.0
      광주            263.0   250.0    4.0      0.0     0.0    8.0
      대전            219.8   203.0    1.0      0.0     9.0    6.0
      울산            187.4   185.0    1.0      0.0     0.0    2.0
      경기           2226.8  2035.0   78.0     31.0    22.0   60.0
      강원            207.4   189.0    4.0      1.0     1.0   12.0
      충북            279.8   243.0   21.0      0.0    16.0    0.0
      충남            305.8   301.0    1.0      0.0     1.0    3.0
      전북            292.8   277.0    0.0      0.0     2.0   14.0
      전남            279.7   257.0   13.0      2.0     0.0    8.0
      경북            318.2   300.0    7.0      3.0     1.0    6.0
      경남            501.1   490.0    0.0      0.0     0.0   11.0
      제주             84.5    79.0    2.0      1.0     1.0    1.0
      세종             88.1    62.0    5.0     11.0     8.0    3.0
가구원수1 1인가구          951.3   898.0   11.0      6.0    10.0   28.0
      2인가구         1947.3  1873.0   14.0      8.0    14.0   41.0
      3인이상가구       5395.1  4926.0  194.0     59.0    76.0  140.0

In [23]:
# 데스크톱 컴퓨터와 노트북 컬럼 합치기 새로운 컬럼으로 합치기 및 기존 컬럼 지우기

ott_2020["컴퓨터"] = ott_2020["데스크톱컴퓨터"] + ott_2020["노트북컴퓨터"]
#del ott_2020["데스크톱컴퓨터"]
#del ott_2020["노트북컴퓨터"] 

ott_2021["컴퓨터"] = ott_2021["데스크톱컴퓨터"] + ott_2021["노트북컴퓨터"]
#del ott_2021["데스크톱컴퓨터"]
#del ott_2021["노트북컴퓨터"] 

########################

# 노트북과 데스크탑 컴퓨터에 대한 컬럼은 전처리 중에 합치려고 했지만
# 회의 후 노트북은 데스크탑 컴퓨터와 달리 휴대성이라는 특성이 있기 때문에 데스크탑 컴퓨터와 합치지 않기로 했다.

NameError: name 'ott_2020' is not defined

In [24]:
# outer join으로 2021, 2020 합치기
ott_medium_20_21=pd.concat([m_20,m_21], axis=1) 
ott_medium_20_21

# 중간 저장
#ott_medium_20_21.to_csv("../project_data_raw/.csv", index = False)

                    명 수    스마트폰  태블릿PC  데스크톱컴퓨터  노트북컴퓨터    TV     명 수    스마트폰  \
전체    소계           7434  7166.0   67.0     74.0    59.0  67.0  8293.7  7697.0
성별    남            3872  3717.0   35.0     50.0    35.0  35.0  4283.5  4018.0
      여            3562  3452.0   32.0     21.0    25.0  36.0  4010.2  3681.0
연령    만10대미만        173   148.0   16.0      0.0     4.0   4.0   174.5   107.0
      만10-19세       825   770.0   12.0     16.0    12.0  14.0   880.1   767.0
      만20-29세      1378  1308.0   26.0     17.0    26.0   1.0  1381.4  1243.0
      만30-39세      1420  1403.0    1.0     14.0     0.0   3.0  1390.1  1326.0
      만40-49세      1481  1445.0    4.0      7.0     6.0  19.0  1585.9  1480.0
      만50-59세      1373  1333.0    3.0     14.0     5.0  19.0  1580.6  1508.0
      만60-69세       666   648.0    5.0      2.0     3.0   7.0  1025.7  1001.0
      만70세이상        119   117.0    0.0      1.0     0.0   1.0   275.5   268.0
월평균소득 소득없음         2477  2346.0   40.0     27.0    30.0  35.0  2631.2  2342.0
      50만원미만        138   133.0    3.0      0.0     1.0   0.0   175.9   166.0
      50-100만원미만    222   218.0    0.0      1.0     3.0   0.0   317.8   302.0
      100-200만원미만  1120  1095.0    9.0      6.0     1.0   8.0  1094.2  1044.0
      200-300만원미만  1961  1910.0    8.0     20.0    12.0  12.0  2118.0  2010.0
      300-400만원미만  1026  1002.0    3.0     10.0     4.0   5.0  1326.0  1262.0
      400-500만원미만   266   253.0    3.0      3.0     2.0   5.0   358.2   326.0
      500만원이상       224   212.0    0.0      3.0     6.0   3.0   272.5   247.0
지역    서울           1482  1429.0   13.0     10.0    13.0  16.0  1626.1  1517.0
      부산            524   520.0    0.0      0.0     2.0   2.0   555.7   551.0
      대구            335   299.0   13.0      9.0     8.0   5.0   358.0   301.0
      인천            452   435.0    7.0      3.0     3.0   4.0   499.5   456.0
      광주            248   243.0    1.0      2.0     1.0   0.0   263.0   250.0
      대전            213   212.0    1.0      0.0     0.0   0.0   219.8   203.0
      울산            176   172.0    0.0      4.0     0.0   1.0   187.4   185.0
      경기           1907  1823.0   15.0     29.0    13.0  27.0  2226.8  2035.0
      강원            181   159.0    9.0      1.0     7.0   6.0   207.4   189.0
      충북            264   260.0    0.0      3.0     1.0   0.0   279.8   243.0
      충남            265   259.0    0.0      4.0     0.0   1.0   305.8   301.0
      전북            262   260.0    0.0      1.0     0.0   1.0   292.8   277.0
      전남            245   245.0    0.0      0.0     0.0   0.0   279.7   257.0
      경북            291   271.0    5.0      5.0     8.0   3.0   318.2   300.0
      경남            427   426.0    0.0      0.0     0.0   1.0   501.1   490.0
      제주             83    79.0    0.0      1.0     1.0   1.0    84.5    79.0
      세종             79    79.0    0.0      0.0     0.0   0.0    88.1    62.0
가구원수1 1인가구          822   810.0    0.0      5.0     7.0   0.0   951.3   898.0
      2인가구         1586  1553.0   10.0      5.0    13.0   6.0  1947.3  1873.0
      3인이상가구       5027  4806.0   55.0     60.0    40.0  60.0  5395.1  4926.0

                   태블릿PC  데스크톱컴퓨터  노트북컴퓨터     TV
전체    소계           216.0     66.0   100.0  207.0
성별    남             99.0     47.0    43.0   77.0
      여            120.0     20.0    56.0  132.0
연령    만10대미만        50.0      1.0     2.0   15.0
      만10-19세       46.0     24.0    31.0   13.0
      만20-29세       64.0     15.0    41.0   19.0
      만30-39세       35.0      1.0     6.0   22.0
      만40-49세       14.0     14.0     8.0   71.0
      만50-59세        6.0     13.0     9.0   46.0
      만60-69세        3.0      2.0     4.0   15.0
      만70세이상         0.0      1.0     0.0    6.0
월평균소득 소득없음         129.0     37.0    50.0   76.0
      50만원미만         5.0      1.0     1.0    4.0
      50-100만원미만     4.0      9.0     0.0    3.0
      100-200만원미만   14.0      3.0     4.0   27.0
      200-300만원미만   23.0      6.0    28.0   49.0
      300-400만원미만   30.0      3.0     9.0   21.0
      400-500만원미만    9.0      3.0     3.0   18.0
      500만원이상        4.0      7.0     5.0    9.0
지역    서울            39.0      7.0    15.0   49.0
      부산             0.0      2.0     0.0    2.0
      대구            27.0      5.0    10.0   14.0
      인천            14.0      7.0    12.0    9.0
      광주             4.0      0.0     0.0    8.0
      대전             1.0      0.0     9.0    6.0
      울산             1.0      0.0     0.0    2.0
      경기            78.0     31.0    22.0   60.0
      강원             4.0      1.0     1.0   12.0
      충북            21.0      0.0    16.0    0.0
      충남             1.0      0.0     1.0    3.0
      전북             0.0      0.0     2.0   14.0
      전남            13.0      2.0     0.0    8.0
      경북             7.0      3.0     1.0    6.0
      경남             0.0      0.0     0.0   11.0
      제주             2.0      1.0     1.0    1.0
      세종             5.0     11.0     8.0    3.0
가구원수1 1인가구          11.0      6.0    10.0   28.0
      2인가구          14.0      8.0    14.0   41.0
      3인이상가구       194.0     59.0    76.0  140.0